
stages:
  - build
  - test
  - deploy
build:
  stage: build
  image: docker
  services:
    - docker:dind
  script:
    # - docker login -u $CI_REGISTRY_USER $CI_REGISTRY --password=$CI_REGISTRY_PASSWORD
    # - echo $CI_REGISTRY_IMAGE
    # - docker pull registry.gitlab.com/tin280/todolist
    - docker images
    - docker build -t test
test:
  stage: test
  image: docker
  services:
    - docker:dind
  script:
    - docker images
    - docker run test
    - docker images
pages:
  stage: deploy
  image: node:14-alpine
  script: 
    - rm -rf .public
    - mkdir .public
    - cp -r * .public
    - mv .public public
  artifacts:
    paths:
      - public
  only:
    - dev