
stages:
  - build
  - test
  - deploy
build:
  stage: build
  image: docker
  services:
    - docker:dind
  script:
    - docker login -u $CI_REGISTRY_USER $CI_REGISTRY --password=$CI_REGISTRY_PASSWORD
    - docker login registry.gitlab.com
    - docker build -t registry.gitlab.com/tin280/todolist .
    - docker push registry.gitlab.com/tin280/todolist
    - docker images
test:
  stage: test
  image: docker
  services:
    - docker:dind
  script:
    - docker images
    - docker run $CI_REGISTRY_IMAGE
    - docker images
pages:
  stage: deploy
  image: node:14-alpine
  script: 
    - rm -rf .public
    - mkdir .public
    - cp -r * .public
    - mv .public public
  artifacts:
    paths:
      - public
  only:
    - dev